### ISSUE TITLE
Release version & push container to Docker Hub

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx-postgis-conversion#22]
- [x] Test release and container(s)
- [x] Release new version
- [x] Fetch & test container build by Docker Hub (Docker watches the master branch) [bootstrap](https://hub.docker.com/r/geometalab/osmaxx-postgis-conversion-bootstrap/)/[conversion](https://hub.docker.com/r/geometalab/osmaxx-postgis-conversion-export/)

**Comment by njordan-hsr** [comment]
Dockerhub _listens_ to the develop branch, if you push (ie. merge pull requests), it builds automatically. I wouldn't recommend changing that mechanism, otherwise we have another thing to remember whenever we're changing something.

If we really want a release process for this, I suggest the following:

* make Dockerhub watch the master branch
* run tests(?) on the develop branch, if they pass, create a new release (including pushing develop onto master, which is what git flow already suggests)

**Comment by wasabideveloper** [comment]
No, no no. I just forgot that. It's ok the way it works. I reworked the description.

**Comment by njordan-hsr** [comment]
OK :)

**Comment by njordan-hsr** [comment]
Released Version 0.1
